steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '--privileged', 'tonistiigi/binfmt', '--install', 'all']
    id: qemu

  - name: 'gcr.io/cloud-builders/docker'
    args: ['buildx', 'create', '--name', 'multiarch', '--driver', 'docker-container', '--use']
    id: buildx-create
    waitFor: ['qemu']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['buildx', 'inspect', '--bootstrap']
    id: buildx-bootstrap
    waitFor: ['buildx-create']

  - name: 'bash'
    args:
      - -c
      - |
        echo "${_IMG_TAG}" > .version
    id: version

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'buildx'
      - 'build'
      - '--builder=multiarch'
      - '--platform=linux/amd64,linux/arm64'
      - '--cache-from=type=registry,ref=us-central1-docker.pkg.dev/$PROJECT_ID/docuseal/docuseal:buildcache'
      - '--cache-to=type=registry,ref=us-central1-docker.pkg.dev/$PROJECT_ID/docuseal/docuseal:buildcache,mode=max'
      - '--tag=us-central1-docker.pkg.dev/$PROJECT_ID/docuseal/docuseal:${_IMG_TAG}'
      - '--tag=us-central1-docker.pkg.dev/$PROJECT_ID/docuseal/docuseal:latest'
      - '--push'
      - '.'
    waitFor: ['buildx-bootstrap', 'version']

substitutions:
  _IMG_TAG: 'latest'

options:
  machineType: E2_HIGHCPU_32
  logging: CLOUD_LOGGING_ONLY

images: []
timeout: 7200s
